[tool.bumpversion]
current_version = "0.0.3"
commit = true
tag = true
tag_name = "{new_version}"
message = "Use the Force, Luke. Bump version: {current_version} → {new_version}"

[[tool.bumpversion.files]]
filename = "SwiftUIFoundation.podspec"

